run:
  skip-files:
    - ".*\\.tpl\\.go$"

linters-settings:
  funlen:
    lines: 150
    statements: 105

linters:
  enable:
    - bodyclose
    # - dupl # USELESS until code templating can be replaced by generics (Go v2)
    - errorlint
    - exhaustive
    # - exhaustivestruct # OUTDATED
    - exportloopref
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    # - gosec # CANNOT use until gosec options can be configured here: https://github.com/golangci/golangci-lint/issues/177
    # - interfacer # WRONG warnings and deprecated by the author https://github.com/golangci/golangci-lint/issues/1689
    - prealloc
    # - scopelint # OUTDATED
    - unconvert
    - unparam
